### PR TITLE
Resize all 128x128 inventory textures files to 64x64

### PR DESCRIPTION
**Pull request by ObaniGemini**
I used the resolution with what we resized report button for all unified_inventory buttons.
Putting this in a PR to prevent eventual problems with unified_inventory.

**470kb -> 201kb**

### CODE REVIEW

**Comment by BetterToAutomateTheWorld** [comment]
Good idea, +1 for me

**Comment by BetterToAutomateTheWorld** [comment]
But, this repository isn't used at all, each version of unified_inventory in our servers is different...

**Comment by ObaniGemini** [comment]
So bad... Anyway I'm working on a totally reworked version of u_inv textures, with easier textures and lighter. Maybe shall I close the issue ?

**Comment by aerozoic** [comment]
This is a good idea. I can resize the u_inv textures for SB server unless you want to do it yourself @ObaniGemini

**Comment by ObaniGemini** [comment]
@cessna151 All the u_inv textures were already resized in that PR :)
But I'll do something better soon :)

**Comment by Lymkwi** [comment]
> But, this repository isn't used at all, each version of unified_inventory in our servers is different...

Let's unify unified inventory then. (this was a terrible pun)
I will create one branch for each server and let master be the default one from which updates and general modifications applying to all servers will be made. This process will (slowly) be repeated for all our fork's submodules throughout all the servers' repositories.

**Comment by ObaniGemini** [comment]
Yeah, thought u_inv was the same version for each repo but no :/
Anyway, you should wait the reworked texture patch before merging, create a separated branch is a good idea, I would be glad if you did this :) ( I'm a pure poo to that kind of things, and to many others)

**Comment by Lymkwi** [comment]
Too late it's already done... Thankfully your PR still seems okay. Your modifications will be merged for all servers.

**Comment by ObaniGemini** [comment]
Too bad, so there will be a second turn :)

**Comment by BetterToAutomateTheWorld** [comment]
That's beautiful ! Thank you so much for your work :+1: 
:dango: :heart: :kiss: :smile_cat: 

(Mélanie ;p)

**Comment by ObaniGemini** [comment]
Thank you for your comments, as if it's on the wrong PR :p

EDIT : I did shit with my PRs organization ^^

**Pull request closed without merging**
